base_url = "https://hucsmn.com"

title = "hucsmn"
description = "random thoughts on programming"
theme = "zola-pickles"

taxonomies = [
  {name = "tags", feed = true},
  {name = "categories", paginate_by = 5},
]

compile_sass = true
build_search_index = true
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "gruvbox-light"

[extra]
subtitle = "random thoughts on programming"
menu_links = [
    { url = "$BASE_URL/about", name = "关于" },
    { url = "$BASE_URL/categories", name = "分类" },
    { url = "$BASE_URL/tags", name = "标签" },
]
copyright = "Copyright © 2021 hucsmn"
katex_enable = false
instantpage_enable = true
